name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches: [master]  # nebo jiná tvoje hlavní větev

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Doxygen
              run: sudo apt-get update && sudo apt-get install doxygen -y

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5

            - name: Generate Doxygen documentation
              run: doxygen Doxyfile

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./docs/html

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
